import api from './axios';
export const adminStats = () => api.get('/admin/stats');
export const adminPlans = () => api.get('/admin/plans');
export const createAdminPlan = (payload) => api.post('/admin/plans', payload);
export const updateAdminPlan = (id, payload) => api.put(`/admin/plans/${id}`, payload);
export const deleteAdminPlan = (id) => api.delete(`/admin/plans/${id}`);
export const adminMembers = (params) => api.get('/admin/members', { params });
export const createAdminMember = (payload) => api.post('/admin/members', payload);
export const updateAdminMember = (id, payload) => api.put(`/admin/members/${id}`, payload);
export const deleteAdminMember = (id) => api.delete(`/admin/members/${id}`);
export const adminTrainers = () => api.get('/admin/trainers');
export const createAdminTrainer = (payload) => api.post('/admin/trainers', payload);
export const updateAdminTrainer = (id, payload) => api.put(`/admin/trainers/${id}`, payload);
export const deleteAdminTrainer = (id) => api.delete(`/admin/trainers/${id}`);
export const adminEquipment = () => api.get('/admin/equipment');
export const createAdminEquipment = (payload) => api.post('/admin/equipment', payload);
export const updateAdminEquipment = (id, payload) => api.put(`/admin/equipment/${id}`, payload);
export const deleteAdminEquipment = (id) => api.delete(`/admin/equipment/${id}`);
export const adminMaintenance = () => api.get('/admin/maintenance');
export const adminMaintenanceLookups = () => api.get('/admin/maintenance/lookups');
export const createAdminMaintenance = (payload) => api.post('/admin/maintenance', payload);
export const updateAdminMaintenance = (id, payload) => api.put(`/admin/maintenance/${id}`, payload);
export const deleteAdminMaintenance = (id) => api.delete(`/admin/maintenance/${id}`);
export const adminPromotions = () => api.get('/admin/promotions');
export const createAdminPromotion = (payload) => api.post('/admin/promotions', payload);
export const updateAdminPromotion = (id, payload) => api.put(`/admin/promotions/${id}`, payload);
export const deleteAdminPromotion = (id) => api.delete(`/admin/promotions/${id}`);
export const adminOrders = () => api.get('/admin/orders');
export const updateAdminOrder = (id, payload) => api.put(`/admin/orders/${id}`, payload);
export const deleteAdminOrder = (id) => api.delete(`/admin/orders/${id}`);
